Fixed snapshots and some params
proxima-one/stream-client-js pull request #13
Opened 2023-04-12 10:46 UTC by sn0wyQ

2023-04-12 12:17 UTC, kalabukdima requested changes

2023-04-12 12:17 UTC, kalabukdima commented on test/client.e2e.ts
> +const streamDbUri = "0.0.0.0:50051";
This won't work in the CI. It's important that these tests check the status of our buh cluster

2023-04-13 07:17 UTC, kalabukdima approved these changes

2023-04-13 08:08 UTC, sn0wyQ commented
https://github.com/proxima-one/stream-client-js/actions/runs/4686951041

2023-04-13 08:09 UTC, merged